### ISSUE TITLE
Parser error Couldn't parse params file

### ISSUE THREAD

**Issue by EliasB23** [ros-controls/gazebo_ros2_control#141]
Hello, this is my first post so feel free to correct if I miss anything or ask for extra info. 
System Info: 
-SO: Ubuntu 20.04 (on VirtualBox)
-ROS 2 Foxy 

Error: 
While trying to load a simulation using Gazebo Classic (11), the log shows, between many other things, that it couldn't parse the ros_controller.yaml from de urdf (I checked it), I'm not doing anything different from the examples and yet it doesn't load. If I try loading a only the gazebo and spawn entity, it doesn't load the model, but if I load everything (gazebo+rviz+moveit+ros_control) it loads failing only to parse de .yaml. 

the last part of the .urdf:
`<ros2_control name="GazeboSystem" type="system">
      <hardware>
        <plugin>fake_components/GenericSystem</plugin>
      </hardware>
      <joint name="joint1_base">
        <command_interface name="position">
          <param name="min">0</param>
          <param name="max">6.28</param>
        </command_interface>
        <state_interface name="position">
          <param name="initial_value">1.0</param>
        </state_interface>
        <state_interface name="velocity"/>
      </joint>
      <joint name="joint2_arm1">
        <command_interface name="position">
          <param name="min">-1.57</param>
          <param name="max">1.57</param>
        </command_interface>
        <state_interface name="position">
          <param name="initial_value">1.0</param>
        </state_interface>
        <state_interface name="velocity"/>
      </joint>
      <joint name="joint3_arm2">
        <command_interface name="position">
          <param name="min">0</param>
          <param name="max">3.1415</param>
        </command_interface>
        <state_interface name="position">
          <param name="initial_value">1.0</param>
        </state_interface>
        <state_interface name="velocity"/>
      </joint>
      <joint name="joint4_arm3">
        <command_interface name="position">
          <param name="min">0</param>
          <param name="max">3.1415</param>
        </command_interface>
        <state_interface name="position">
          <param name="initial_value">1.0</param>
        </state_interface>
        <state_interface name="velocity"/>
      </joint>
      <joint name="joint5_end">
        <command_interface name="position">
          <param name="min">0</param>
          <param name="max">6.28</param>
        </command_interface>
        <state_interface name="position">
          <param name="initial_value">1.0</param>
        </state_interface>
        <state_interface name="velocity"/>
      </joint>
    </ros2_control>
    <gazebo>
     <plugin filename="libgazebo_ros2_control.so" name="gazebo">
      <robot_param>robot_description</robot_param>
      <robot_param_node>robot_state_publisher</robot_param_node>
      <parameters>$(find-pkg-prefix gpr_robot_moveit2_config)/config/ros_controllers.yaml</parameters>
     </plugin>
    </gazebo> `

ros_controllers.yaml
`controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_state_controller:
      type: joint_state_controller/JointStateController

arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
     - joint1_base
     - joint2_arm1
     - joint3_arm2
     - joint4_arm3
     - joint5_end
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0

joint_state_controller:
  ros__parameters:
    type: joint_state_controller/JointStateController
`
the launch file: (I exclude some functions and imports to try make it a little shorter, if needed I'll post it full)
`def load_yaml(file_path):
    """Load a yaml file into a dictionary"""
    try:
        with open(file_path, 'r') as file:
            return yaml.safe_load(file)
    except EnvironmentError: # parent of IOError, OSError *and* WindowsError where available
        return None

def generate_launch_description():
    urdf_file = get_package_file('gpr_robot_moveit2_config', 'urdf/gpr.urdf')
    srdf_file = get_package_file('gpr_robot_moveit2_config', 'config/gpr_robot.srdf')
    kinematics_file = get_package_file('gpr_robot_moveit2_config', 'config/kinematics.yaml')
    ompl_config_file = get_package_file('gpr_robot_moveit2_config', 'config/ompl_planning.yaml')
    moveit_controllers_file = get_package_file('gpr_robot_moveit2_config', 'config/controllers.yaml')
    ros_controllers_file = get_package_file('gpr_robot_moveit2_config', 'config/ros_controllers.yaml')
    rviz_config_file= get_package_file('gpr_robot_moveit2_config', 'rviz/rviz.rviz')

    robot_description = load_file(urdf_file)
    robot_description_semantic = load_file(srdf_file)
    kinematics_config = load_yaml(kinematics_file)
    ompl_config = load_yaml(ompl_config_file)

    moveit_controllers = {
        'moveit_simple_controller_manager' : load_yaml(moveit_controllers_file),
        'moveit_controller_manager': 'moveit_simple_controller_manager/MoveItSimpleControllerManager'
    }
    trajectory_execution = {
        'moveit_manage_controllers': True,
        'trajectory_execution.allowed_execution_duration_scaling': 1.2,
        'trajectory_execution.allowed_goal_duration_margin': 0.5,
        'trajectory_execution.allowed_start_tolerance': 0.01
    }
    planning_scene_monitor_config = {
        'publish_planning_scene': True,
        'publish_geometry_updates': True,
        'publish_state_updates': True,
        'publish_transforms_updates': True
    }

    # MoveIt node
    move_group_node = Node(
        package='moveit_ros_move_group',
        executable='move_group',
        output='screen',
        parameters=[
            {
                'robot_description': robot_description,
                'robot_description_semantic': robot_description_semantic,
                'robot_description_kinematics': kinematics_config,
                'ompl': ompl_config,
                'planning_pipelines': ['ompl'],
            },
            moveit_controllers,
            trajectory_execution,
            planning_scene_monitor_config,
        ],
        arguments='-pose home',
    )
    #*GUI JointStateController racing vs moveit2
    #joint_state_publisher_gui_node = Node(
    #    package='joint_state_publisher_gui',
    #    executable='joint_state_publisher_gui',
    #    name='joint_state_publisher_gui',
    #)USE FOR MANUAL CONTROL OF JOINTS IN RVIZ (FOR NOW)
    # TF information
    robot_state_publisher = Node(
        name='robot_state_publisher',
        package='robot_state_publisher',
        executable='robot_state_publisher',
        output='screen',
        parameters=[
            {'robot_description': robot_description}
        ]
    )
    # Visualization (parameters needed for MoveIt display plugin)
    
    rviz = Node(
        name='rviz',
        package='rviz2',
        executable='rviz2',
        output='screen',
        arguments=["-d", rviz_config_file],
        parameters=[
            {
                'robot_description': robot_description,
                'robot_description_semantic': robot_description_semantic,
                'robot_description_kinematics': kinematics_config,
            }
        ],
    )
    # Controller manager for realtime interactions
    ros2_control_node = Node(
        package="controller_manager",
        executable="ros2_control_node",
        parameters= [
            {'robot_description': robot_description},
            ros_controllers_file
        ],
        output="screen",
    )
    # Startup up ROS2 controllers (will exit immediately)
    controller_names = ['arm_controller', 'joint_state_controller']
    spawn_controllers = [
        Node(
            package="controller_manager",
            executable="spawner.py",
            arguments=[controller],
            output="screen")
        for controller in controller_names
    ]

    #Gazebo11 start
    install_dir = get_package_prefix('gpr_robot_moveit2_config')
    model_path = os.path.join(get_package_share_directory('gpr_robot_moveit2_config'),'models')
    print("urdf_file_name : {}".format(urdf_file))
    if 'GAZEBO_MODEL_PATH' in os.environ:
        os.environ['GAZEBO_MODEL_PATH'] = os.environ['GAZEBO_MODEL_PATH'] + ':' + install_dir + '/share'+':' + model_path
    else:
        os.environ['GAZEBO_MODEL_PATH'] = install_dir + '/share' + ':' + model_path
    if 'GAZEBO_PLUGIN_PATH' in os.environ:
        os.environ['GAZEBO_PLUGIN_PATH'] = os.environ['GAZEBO_PLUGIN_PATH'] + ':' + install_dir + '/lib'
    else: 
        os.environ['GAZEBO_PLUGIN_PATH'] = install_dir + '/lib'

    gazebo_ros_pkg = get_package_share_directory('gazebo_ros')
    #gazebo = IncludeLaunchDescription(
    #    PythonLaunchDescriptionSource(
    #        [FindPackageShare('gazebo_ros'), '/launch', '/gazebo.launch.py']
    #    ),
    #)  
    gazebo = ExecuteProcess(cmd=['gazebo', '--verbose', '-s' ,'libgazebo_ros_init.so','-s' ,'libgazebo_ros_factory.so', '-s', 'libgazebo_ros_force_system.so'], output='screen')
    #'/home/elias/ros2_ws/src/gpr_robot_moveit2_config/models/gpr/gpr.world' , '-s', 'libgazebo_ros_state.so'
    spawn_entity = Node(package='gazebo_ros', executable='spawn_entity.py',
                        name='urdf_spawner',
                        arguments=['-topic', 'robot_description',
                                   '-entity', 'gpr_robot'],
                        output='screen')

    return LaunchDescription([
        move_group_node,
        robot_state_publisher,
        ros2_control_node,
        rviz,
        gazebo,
        spawn_entity,
        ] + spawn_controllers
    )`

the log full: 
`ros2 launch gpr_robot_moveit2_config my_planning_execution.launch.py
[INFO] [launch]: All log files can be found below /home/elias/.ros/log/2022-07-15-15-28-15-291557-elias-VirtualBox-1997
[INFO] [launch]: Default logging verbosity is set to INFO
urdf_file_name : /home/elias/ros2_ws/install/gpr_robot_moveit2_config/share/gpr_robot_moveit2_config/urdf/gpr.urdf
[INFO] [move_group-1]: process started with pid [1999]
[INFO] [robot_state_publisher-2]: process started with pid [2001]
[INFO] [ros2_control_node-3]: process started with pid [2003]
[INFO] [rviz2-4]: process started with pid [2005]
[INFO] [gazebo-5]: process started with pid [2007]
[INFO] [spawn_entity.py-6]: process started with pid [2009]
[INFO] [spawner.py-7]: process started with pid [2011]
[INFO] [spawner.py-8]: process started with pid [2013]
[ros2_control_node-3] [INFO] [1657909695.820328967] [controller_manager]: update rate is 100 Hz
[robot_state_publisher-2] Parsing robot urdf xml string.
[robot_state_publisher-2] Link link0_base had 1 children
[robot_state_publisher-2] Link link1_base had 1 children
[robot_state_publisher-2] Link link2_arm1 had 1 children
[robot_state_publisher-2] Link link3_arm2 had 1 children
[robot_state_publisher-2] Link link4_arm3 had 1 children
[robot_state_publisher-2] Link link5_end had 0 children
[robot_state_publisher-2] [INFO] [1657909695.830261023] [robot_state_publisher]: got segment link0_base
[robot_state_publisher-2] [INFO] [1657909695.830399196] [robot_state_publisher]: got segment link1_base
[robot_state_publisher-2] [INFO] [1657909695.830421188] [robot_state_publisher]: got segment link2_arm1
[robot_state_publisher-2] [INFO] [1657909695.830433974] [robot_state_publisher]: got segment link3_arm2
[robot_state_publisher-2] [INFO] [1657909695.830447357] [robot_state_publisher]: got segment link4_arm3
[robot_state_publisher-2] [INFO] [1657909695.830460141] [robot_state_publisher]: got segment link5_end
[robot_state_publisher-2] [INFO] [1657909695.830473232] [robot_state_publisher]: got segment world
[move_group-1] [WARN] [1657909695.980134176] [move_group.move_group]: MoveGroup launched without ~default_planning_pipeline specifying the namespace for the default planning pipeline configuration
[move_group-1] [WARN] [1657909695.980208408] [move_group.move_group]: Using default pipeline 'ompl'
[move_group-1] Parsing robot urdf xml string.
[move_group-1] [INFO] [1657909695.996208474] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.00141317 seconds
[move_group-1] [INFO] [1657909695.996310710] [moveit_robot_model.robot_model]: Loading robot model 'gpr_robot'...
[move_group-1] [INFO] [1657909695.996331473] [moveit_robot_model.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[move_group-1] Link link0_base had 1 children
[move_group-1] Link link1_base had 1 children
[move_group-1] Link link2_arm1 had 1 children
[move_group-1] Link link3_arm2 had 1 children
[move_group-1] Link link4_arm3 had 1 children
[move_group-1] Link link5_end had 0 children
[move_group-1] [INFO] [1657909696.103146734] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
[move_group-1] [INFO] [1657909696.103357267] [moveit.ros_planning_interface.moveit_cpp]: Listening to 'joint_states' for joint states
[move_group-1] [INFO] [1657909696.104709097] [moveit_ros.current_state_monitor]: Listening to joint states on topic 'joint_states'
[move_group-1] [INFO] [1657909696.106068892] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/attached_collision_object' for attached collision objects
[move_group-1] [INFO] [1657909696.106266117] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[move_group-1] [INFO] [1657909696.107229410] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/planning_scene'
[move_group-1] [INFO] [1657909696.107269026] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[move_group-1] [INFO] [1657909696.108796502] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'collision_object'
[move_group-1] [INFO] [1657909696.110092554] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'planning_scene_world' for planning scene world geometry
[move_group-1] [WARN] [1657909696.110358016] [moveit.ros.occupancy_map_monitor]: Resolution not specified for Octomap. Assuming resolution = 0.1 instead
[move_group-1] [ERROR] [1657909696.110414695] [moveit.ros.occupancy_map_monitor]: No 3D sensor plugin(s) defined for octomap updates
[move_group-1] [INFO] [1657909696.115431771] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'ompl'
[move_group-1] [INFO] [1657909696.120788360] [moveit.ros_planning.planning_pipeline]: Multiple planning plugins available. You should specify the '~planning_plugin' parameter. Using 'chomp_interface/CHOMPPlanner' for now.
[move_group-1] [INFO] [1657909696.140071639] [moveit.ros_planning.planning_pipeline]: Using planning interface 'CHOMP'
[ros2_control_node-3] [INFO] [1657909696.414146188] [controller_manager]: Loading controller 'arm_controller'
[ros2_control_node-3] [INFO] [1657909696.496235721] [controller_manager]: Loading controller 'joint_state_controller'
[spawner.py-7] [INFO] [1657909696.496399973] [spawner_arm_controller]: Loaded arm_controller
[ros2_control_node-3] Warning: class_loader.impl: SEVERE WARNING!!! A namespace collision has occured with plugin factory for class joint_state_broadcaster::JointStateBroadcaster. New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
[ros2_control_node-3]          at line 253 in /opt/ros/foxy/include/class_loader/class_loader_core.hpp
[ros2_control_node-3] [INFO] [1657909696.551161079] [controller_manager]: Configuring controller 'arm_controller'
[ros2_control_node-3] [INFO] [1657909696.551302941] [arm_controller]: Command interfaces are [position] and and state interfaces are [position velocity].
[ros2_control_node-3] [INFO] [1657909696.552654058] [arm_controller]: Controller state will be published at 100.00 Hz.
[ros2_control_node-3] [INFO] [1657909696.553927823] [arm_controller]: Action status changes will be monitored at 20.00 Hz.
[move_group-1] [INFO] [1657909696.563256054] [moveit.plugins.moveit_simple_controller_manager]: Added FollowJointTrajectory controller for arm_controller
[move_group-1] [INFO] [1657909696.563526482] [moveit.plugins.moveit_simple_controller_manager]: Returned 1 controllers in list
[move_group-1] [INFO] [1657909696.564418197] [moveit_ros.trajectory_execution_manager]: Trajectory execution is managing controllers
[move_group-1] [INFO] [1657909696.564453847] [move_group.move_group]: MoveGroup debug mode is ON
[spawner.py-7] [INFO] [1657909696.581990824] [spawner_arm_controller]: Configured and started arm_controller
[spawner.py-8] [INFO] [1657909696.623283879] [spawner_joint_state_controller]: Loaded joint_state_controller
[ros2_control_node-3] [INFO] [1657909696.639607830] [controller_manager]: Configuring controller 'joint_state_controller'
[spawner.py-8] [INFO] [1657909696.672516279] [spawner_joint_state_controller]: Configured and started joint_state_controller
[INFO] [spawner.py-7]: process has finished cleanly [pid 2011]
[move_group-1] [INFO] [1657909696.738750149] [move_group.move_group]: 
[move_group-1] 
[move_group-1] ********************************************************
[move_group-1] * MoveGroup using: 
[move_group-1] *     - ApplyPlanningSceneService
[move_group-1] *     - ClearOctomapService
[move_group-1] *     - CartesianPathService
[move_group-1] *     - ExecuteTrajectoryAction
[move_group-1] *     - GetPlanningSceneService
[move_group-1] *     - KinematicsService
[move_group-1] *     - MoveAction
[move_group-1] *     - MotionPlanService
[move_group-1] *     - QueryPlannersService
[move_group-1] *     - StateValidationService
[move_group-1] ********************************************************
[move_group-1] 
[move_group-1] [INFO] [1657909696.742079563] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context using planning plugin chomp_interface/CHOMPPlanner
[move_group-1] [INFO] [1657909696.742847711] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context initialization complete
[move_group-1] Loading 'move_group/ApplyPlanningSceneService'...
[move_group-1] Loading 'move_group/ClearOctomapService'...
[move_group-1] Loading 'move_group/MoveGroupCartesianPathService'...
[move_group-1] Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
[move_group-1] Loading 'move_group/MoveGroupGetPlanningSceneService'...
[move_group-1] Loading 'move_group/MoveGroupKinematicsService'...
[move_group-1] Loading 'move_group/MoveGroupMoveAction'...
[move_group-1] Loading 'move_group/MoveGroupPlanService'...
[move_group-1] Loading 'move_group/MoveGroupQueryPlannersService'...
[move_group-1] Loading 'move_group/MoveGroupStateValidationService'...
[move_group-1] 
[move_group-1] You can start planning now!
[move_group-1] 
[INFO] [spawner.py-8]: process has finished cleanly [pid 2013]
[rviz2-4] [INFO] [1657909696.949321174] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-4] [INFO] [1657909696.949489709] [rviz2]: OpenGl version: 3.1 (GLSL 1.4)
[spawn_entity.py-6] [INFO] [1657909697.019314691] [urdf_spawner]: Spawn Entity started
[spawn_entity.py-6] [INFO] [1657909697.020562313] [urdf_spawner]: Loading entity published on topic robot_description
[spawn_entity.py-6] [INFO] [1657909697.033649963] [urdf_spawner]: Waiting for entity xml on robot_description
[spawn_entity.py-6] [INFO] [1657909697.051125844] [urdf_spawner]: Waiting for service /spawn_entity, timeout = 30
[spawn_entity.py-6] [INFO] [1657909697.052852292] [urdf_spawner]: Waiting for service /spawn_entity
[rviz2-4] [INFO] [1657909697.089320162] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-4] Warning: class_loader.impl: SEVERE WARNING!!! A namespace collision has occured with plugin factory for class rviz_default_plugins::displays::InteractiveMarkerDisplay. New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
[rviz2-4]          at line 253 in /opt/ros/foxy/include/class_loader/class_loader_core.hpp
[gazebo-5] Gazebo multi-robot simulator, version 11.11.0
[gazebo-5] Copyright (C) 2012 Open Source Robotics Foundation.
[gazebo-5] Released under the Apache 2 License.
[gazebo-5] http://gazebosim.org
[gazebo-5] 
[gazebo-5] Gazebo multi-robot simulator, version 11.11.0
[gazebo-5] Copyright (C) 2012 Open Source Robotics Foundation.
[gazebo-5] Released under the Apache 2 License.
[gazebo-5] http://gazebosim.org
[gazebo-5] 
[gazebo-5] [Msg] Waiting for master.
[gazebo-5] [Msg] Connected to gazebo master @ http://127.0.0.1:11345
[gazebo-5] [Msg] Publicized address: 172.31.22.7
[gazebo-5] [Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/elias/.gazebo/models/fivedof_description"
[gazebo-5] [Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/elias/.gazebo/models/gpr_linked"
[gazebo-5] [Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/elias/.gazebo/models/gpr_linked_moveit_config"
[gazebo-5] [Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/elias/ros2_ws/install/gpr_robot_moveit2_config/share/ament_index"
[gazebo-5] [Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/elias/ros2_ws/install/gpr_robot_moveit2_config/share/colcon-core"
[gazebo-5] [Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/elias/ros2_ws/install/gpr_robot_moveit2_config/share/gpr_robot_moveit2_config"
[gazebo-5] [Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/elias/ros2_ws/install/gpr_robot_moveit2_config/share/gpr_robot_moveit2_config/models/gpr"
[gazebo-5] [Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/elias/catkin_ws/build"
[gazebo-5] [Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/elias/catkin_ws/devel"
[gazebo-5] [Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/elias/catkin_ws/gprMoveitViejo"
[gazebo-5] [Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/elias/catkin_ws/gpr_robot_description"
[gazebo-5] [Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/elias/catkin_ws/src"
[rviz2-4] [ERROR] [1657909701.731330639] [moveit_ros_visualization.motion_planning_frame]: Action server: /recognize_objects not available
[spawn_entity.py-6] [INFO] [1657909702.100543460] [urdf_spawner]: Calling service /spawn_entity
[rviz2-4] Parsing robot urdf xml string.
[rviz2-4] [INFO] [1657909702.144507750] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.00298455 seconds
[rviz2-4] [INFO] [1657909702.145008818] [moveit_robot_model.robot_model]: Loading robot model 'gpr_robot'...
[rviz2-4] [INFO] [1657909702.145065254] [moveit_robot_model.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[rviz2-4] Link link0_base had 1 children
[rviz2-4] Link link1_base had 1 children
[rviz2-4] Link link2_arm1 had 1 children
[rviz2-4] Link link3_arm2 had 1 children
[rviz2-4] Link link4_arm3 had 1 children
[rviz2-4] Link link5_end had 0 children
[rviz2-4] [INFO] [1657909702.297299110] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[rviz2-4] [INFO] [1657909702.302270105] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/monitored_planning_scene'
[spawn_entity.py-6] [INFO] [1657909702.529580811] [urdf_spawner]: Spawn status: SpawnEntity: Successfully spawned entity [gpr_robot]
[gazebo-5] [INFO] [1657909702.622393172] [gazebo_ros2_control]: Loading gazebo_ros2_control plugin
[gazebo-5] [WARN] [1657909702.627344089] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[gazebo-5] [INFO] [1657909702.669172028] [gazebo]: Starting gazebo_ros2_control plugin in namespace: /
[gazebo-5] [INFO] [1657909702.684240613] [gazebo]: Starting gazebo_ros2_control plugin in ros 2 node: gazebo
[gazebo-5] [INFO] [1657909702.685870929] [gazebo]: Loading parameter file $(find-pkg-prefix gpr_robot_moveit2_config)/config/ros_controllers.yaml
[gazebo-5] 
[**gazebo-5] [ERROR] [1657909702.690854445] [gazebo]: parser error Couldn't parse params file: '--params-file $(find-pkg-prefix gpr_robot_moveit2_config)/config/ros_controllers.yaml'. Error: Error opening YAML file, at /tmp/binarydeb/ros-foxy-rcl-yaml-param-parser-1.1.13/src/parser.c:198, at /tmp/binarydeb/ros-foxy-rcl-1.1.13/src/rcl/arguments.c:388
[gazebo-5]** 
[INFO] [spawn_entity.py-6]: process has finished cleanly [pid 2009]
[rviz2-4] [INFO] [1657909703.142402978] [interactive_marker_display_94104070580928]: Connected on namespace: rviz_moveit_motion_planning_display/robot_interaction_interactive_marker_topic
[rviz2-4] Link link0_base had 1 children
[rviz2-4] Link link1_base had 1 children
[rviz2-4] Link link2_arm1 had 1 children
[rviz2-4] Link link3_arm2 had 1 children
[rviz2-4] Link link4_arm3 had 1 children
[rviz2-4] Link link5_end had 0 children
[rviz2-4] [INFO] [1657909703.158824421] [moveit_ros_visualization.motion_planning_frame]: group arm_manipulator
[rviz2-4] [INFO] [1657909703.158865134] [moveit_ros_visualization.motion_planning_frame]: Constructing new MoveGroup connection for group 'arm_manipulator' in namespace ''
[rviz2-4] [WARN] [1657909703.160005911] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[rviz2-4] [INFO] [1657909703.214881471] [move_group_interface]: Ready to take commands for planning group arm_manipulator.
[rviz2-4] [INFO] [1657909703.215268484] [move_group_interface]: Looking around: no
[rviz2-4] [INFO] [1657909703.215293156] [move_group_interface]: Replanning: no
[rviz2-4] [INFO] [1657909703.311747570] [interactive_marker_display_94104070580928]: Sending request for interactive markers
[rviz2-4] [INFO] [1657909703.317053376] [moveit_ros_visualization.motion_planning_frame_planning]: POPULATING PLANNERS 1 grp: arm_manipulator
[rviz2-4] [INFO] [1657909703.318089862] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: CHOMP
[rviz2-4] [INFO] [1657909703.483860484] [interactive_marker_display_94104070580928]: Service response received for initialization
`

If anyone has an idea please let me know. I'm aware that Foxy is not being maintained and I'm trying porting this to humble but it will take me a little more time, and would like to have this working too. 
Thanks in advance!

**Comment by bmagyar** [comment]
I'm sorry but this is not really readable.

First off, I think you have better chances for getting help at https://answers.ros.org/questions, try to always post there first.
Second, try attaching files instead of copying them into a page that tries to format them according to the hieroglyphs it finds in them, that helps readability :D You should also post the commands you used to reproduce the problem to help others see what's up. (You may have done it but it got lost in the text for me)

**Comment by EliasB23** [comment]
I didn't know about attaching files, sorry about that! I will post it in there, thanks!
