### ISSUE TITLE
/odom topic and tf between /odom and /base_link are not published in diff_drive.launch.py 

### ISSUE THREAD

**Issue by TatsukiNishimura** [ros-controls/gazebo_ros2_control#156]
My environments
- Ubuntu 20.04
- ROS2 galactic 
- Gazebo 11

When I run ``` diff_drive.launch.py ```  in gazebo_ros2_control_demos package, I try to see topics ```/odom``` and ```/tf``` with ``` ros2 topic echo ```, but no data was found from ```/odom``` and no tf data between ```/odom``` and ```/base_link```.

I suspect the solution is to set ```use_sim_time``` parameter of ```/controller_manager``` node to true.

**Comment by destogl** [comment]
> I suspect the solution is to set use_sim_time parameter of /controller_manager node to true.

Did you test this solution?
