### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by christophfroehlich** [ros-controls/gazebo_ros2_control#217]
The following link is broken:
https://github.com/ros-controls/gazebo_ros2_control/blob/6458276ca1eaf3ee646afa8e0833386f9785e585/doc/index.rst?plain=1#L289C77-L289C148

Is this section up-to-date? Does one really need Foxy? Can we link to the gazebo_ros2_control_demos at master branch?

**Comment by ahcorde** [comment]
you can remove this, the repository doesn't exists https://github.com/ros-controls/gazebo_ros_demos

**Comment by christophfroehlich** [comment]
But where is this launch file located? I couldn't find any tutorial in the [moveit2 docs](https://moveit.picknik.ai/humble/search.html?q=gazebo&check_keywords=yes&area=default)
```bash
  ros2 launch rrbot_moveit_demo_nodes rrbot_demo.launch.py
```

**Comment by christophfroehlich** [comment]
@ahcorde what do you think? or should I remove this section completely?

**Comment by ahcorde** [comment]
I would say remove
