### ISSUE TITLE
Force Torque data stored in imu vector

### ISSUE THREAD

**Issue by guihomework** [ros-controls/gazebo_ros2_control#218]
This looks like a copy-paste mistake. force torque data are store in the `imu_sensor_data_` when `sim_ft_sensors_` exists.

https://github.com/ros-controls/gazebo_ros2_control/blob/master/gazebo_ros2_control/src/gazebo_system.cpp#L560

I can provide a PR unless there is a reason for this.

**Comment by ahcorde** [comment]
Yep, this look like an error. Happy to review the PR

**Comment by mateusmenezes95** [comment]
Hello @ahcorde and @christophfroehlich. I would like to work on this issue
