### ISSUE TITLE
Passive joints are broken

### ISSUE THREAD

**Issue by christophfroehlich** [ros-controls/gazebo_ros2_control#219]
As a consequence of #177 , passive joints don't work any more (try #172).

The joint is now fixed, even if no command interface is defined.

**Comment by bmagyar** [comment]
That PR was fairly old I think when we merged it, it's not too surprising something wasn't fully aligned.

**Comment by bmagyar** [comment]
I'll make myself a reminder note to never merge wildly unscoped PRs in the future ;)

**Comment by christophfroehlich** [comment]
fixed with #237
