### ISSUE TITLE
Could use remote gazebo  possible?

### ISSUE THREAD

**Issue by JakeFishcode** [ros-controls/gazebo_ros2_control#241]
## Brief
I'm a Gazebo beginner, and I'm currently using ROS 2 control on an NVIDIA Orin platform. Since my remote setup is on an NVIDIA Orin, I'd like to run the control algorithms there. My question is, I want to run Gazebo on my local machine while running ROS 2 code on the Orin, and establish a connection between them using ROS 2 topics (they are on the same local network). Could you please advise if there's a way to achieve this functionality?
## Situation
* Remote: Nvidia AGX Orin (ros2 control and other algorithms)
* Local: Gazebo 
We use issac ros in docker.All the ros2 pkg have to build by self.I just want to test the code. I believe this approach would be quite elegant.

**Comment by christophfroehlich** [comment]
What is the purpose of having ros2_control on the orin but gazebo on the local machine? you want to PIL-test your code, i.e., instead of controlling your hardware it should control your model in gazebo?

**Comment by christophfroehlich** [comment]
As this is not really related to this repository but a general questions I ask you to post your question on [RSE](https://robotics.stackexchange.com/questions), possible answers will be found more easily in the future.
