### ISSUE TITLE
Loading controller failed，Exception thrown during init stage with message: expected [string] got [string_array] 

### ISSUE THREAD

**Issue by PANJIACHENG-98** [ros-controls/gazebo_ros2_control#273]
[INFO] [ros2-4]: process has finished cleanly [pid 20770]
[INFO] [ros2-5]: process started with pid [20814]
[INFO] [ros2-6]: process started with pid [20816]
[INFO] [ros2-7]: process started with pid [20818]
[INFO] [ros2-8]: process started with pid [20820]
[gazebo-1] [INFO] [1706239490.497724358] [controller_manager]: Loading controller 'Head_joint_trajectory_controller'
[gazebo-1] Exception thrown during init stage with message: expected [string] got [string_array] 
[gazebo-1] [ERROR] [1706239490.526122183] [controller_manager]: Could not initialize the controller named 'Head_joint_trajectory_controller'
[gazebo-1] [INFO] [1706239490.541068223] [controller_manager]: Loading controller 'Body_joint_trajectory_controller'
[ros2-8] Error loading controller, check controller_manager logs
[gazebo-1] Exception thrown during init stage with message: expected [string] got [string_array] 
[gazebo-1] [ERROR] [1706239490.558322016] [controller_manager]: Could not initialize the controller named 'Body_joint_trajectory_controller'
[ros2-7] Error loading controller, check controller_manager logs
[gazebo-1] [INFO] [1706239490.575401082] [controller_manager]: Loading controller 'Right_arm_joint_trajectory_controller'
[gazebo-1] Exception thrown during init stage with message: expected [string] got [string_array] 
[gazebo-1] [ERROR] [1706239490.586553576] [controller_manager]: Could not initialize the controller named 'Right_arm_joint_trajectory_controller'
[gazebo-1] [INFO] [1706239490.602357917] [controller_manager]: Loading controller 'Left_arm_joint_trajectory_controller'
[ros2-5] Error loading controller, check controller_manager logs
[gazebo-1] Exception thrown during init stage with message: expected [string] got [string_array] 
[gazebo-1] [ERROR] [1706239490.630282542] [controller_manager]: Could not initialize the controller named 'Left_arm_joint_trajectory_controller'
[ros2-6] Error loading controller, check controller_manager logs
[ERROR] [ros2-8]: process has died [pid 20820, exit code 1, cmd 'ros2 control load_controller --set-state active Head_joint_trajectory_controller'].
[ERROR] [ros2-5]: process has died [pid 20814, exit code 1, cmd 'ros2 control load_controller --set-state active Right_arm_joint_trajectory_controller'].
[ERROR] [ros2-6]: process has died [pid 20816, exit code 1, cmd 'ros2 control load_controller --set-state active Left_arm_joint_trajectory_controller'].
[ERROR] [ros2-7]: process has died [pid 20818, exit code 1, cmd 'ros2 control load_controller --set-state active Body_joint_trajectory_controller'].

**Comment by PANJIACHENG-98** [comment]
robotck@robotckvrm:~/ros2_ws$ ros2 launch dual_arm_gazebo gazebo.launch.py 
[INFO] [launch]: All log files can be found below /home/robotck/.ros/log/2024-01-26-11-24-23-194658-robotckvrm-20684
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [gazebo-1]: process started with pid [20685]
[INFO] [robot_state_publisher-2]: process started with pid [20687]
[INFO] [spawn_entity.py-3]: process started with pid [20689]
[robot_state_publisher-2] [INFO] [1706239463.446393660] [robot_state_publisher]: got segment base_footprint
[robot_state_publisher-2] [INFO] [1706239463.447034647] [robot_state_publisher]: got segment base_link
[robot_state_publisher-2] [INFO] [1706239463.447362213] [robot_state_publisher]: got segment link-Body
[robot_state_publisher-2] [INFO] [1706239463.447632796] [robot_state_publisher]: got segment link-H0
[robot_state_publisher-2] [INFO] [1706239463.447914577] [robot_state_publisher]: got segment link-H1
[robot_state_publisher-2] [INFO] [1706239463.448163628] [robot_state_publisher]: got segment link-J1
[robot_state_publisher-2] [INFO] [1706239463.448521471] [robot_state_publisher]: got segment link-L0
[robot_state_publisher-2] [INFO] [1706239463.448802501] [robot_state_publisher]: got segment link-L1
[robot_state_publisher-2] [INFO] [1706239463.449108173] [robot_state_publisher]: got segment link-L2
[robot_state_publisher-2] [INFO] [1706239463.449449372] [robot_state_publisher]: got segment link-L3
[robot_state_publisher-2] [INFO] [1706239463.449729957] [robot_state_publisher]: got segment link-L4
[robot_state_publisher-2] [INFO] [1706239463.449994481] [robot_state_publisher]: got segment link-L5
[robot_state_publisher-2] [INFO] [1706239463.450271709] [robot_state_publisher]: got segment link-L6
[robot_state_publisher-2] [INFO] [1706239463.450848680] [robot_state_publisher]: got segment link-L7
[robot_state_publisher-2] [INFO] [1706239463.451254760] [robot_state_publisher]: got segment link-R0
[robot_state_publisher-2] [INFO] [1706239463.451519215] [robot_state_publisher]: got segment link-R1
[robot_state_publisher-2] [INFO] [1706239463.451830331] [robot_state_publisher]: got segment link-R2
[robot_state_publisher-2] [INFO] [1706239463.452092579] [robot_state_publisher]: got segment link-R3
[robot_state_publisher-2] [INFO] [1706239463.452427572] [robot_state_publisher]: got segment link-R4
[robot_state_publisher-2] [INFO] [1706239463.452669246] [robot_state_publisher]: got segment link-R5
[robot_state_publisher-2] [INFO] [1706239463.452955135] [robot_state_publisher]: got segment link-R6
[robot_state_publisher-2] [INFO] [1706239463.453194305] [robot_state_publisher]: got segment link-R7
[robot_state_publisher-2] [INFO] [1706239463.453567495] [robot_state_publisher]: got segment world
[gazebo-1] Gazebo multi-robot simulator, version 11.10.2
[gazebo-1] Copyright (C) 2012 Open Source Robotics Foundation.
[gazebo-1] Released under the Apache 2 License.
[gazebo-1] http://gazebosim.org
[gazebo-1] 
[spawn_entity.py-3] [INFO] [1706239463.922335770] [spawn_entity]: Spawn Entity started
[spawn_entity.py-3] [INFO] [1706239463.922793702] [spawn_entity]: Loading entity published on topic robot_description
[spawn_entity.py-3] /opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/qos.py:307: UserWarning: DurabilityPolicy.RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL is deprecated. Use DurabilityPolicy.TRANSIENT_LOCAL instead.
[spawn_entity.py-3]   warnings.warn(
[gazebo-1] Gazebo multi-robot simulator, version 11.10.2
[gazebo-1] Copyright (C) 2012 Open Source Robotics Foundation.
[gazebo-1] Released under the Apache 2 License.
[gazebo-1] http://gazebosim.org
[gazebo-1] 
[spawn_entity.py-3] [INFO] [1706239463.928699469] [spawn_entity]: Waiting for entity xml on robot_description
[spawn_entity.py-3] [INFO] [1706239464.085984963] [spawn_entity]: Waiting for service /spawn_entity, timeout = 30
[spawn_entity.py-3] [INFO] [1706239464.086367444] [spawn_entity]: Waiting for service /spawn_entity
[spawn_entity.py-3] [INFO] [1706239485.144069257] [spawn_entity]: Calling service /spawn_entity
[spawn_entity.py-3] [INFO] [1706239485.408602148] [spawn_entity]: Spawn status: SpawnEntity: Successfully spawned entity [dual_arm]
[INFO] [spawn_entity.py-3]: process has finished cleanly [pid 20689]
[INFO] [ros2-4]: process started with pid [20770]
[gazebo-1] [Msg] Waiting for master.
[gazebo-1] [Msg] Connected to gazebo master @ http://127.0.0.1:11345
[gazebo-1] [Msg] Publicized address: 192.168.122.130
[gazebo-1] [Wrn] [Event.cc:61] Warning: Deleting a connection right after creation. Make sure to save the ConnectionPtr from a Connect call
[gazebo-1] [INFO] [1706239486.984600643] [gazebo_ros2_control]: Loading gazebo_ros2_control plugin
[gazebo-1] [INFO] [1706239486.989064240] [gazebo_ros2_control]: Starting gazebo_ros2_control plugin in namespace: /
[gazebo-1] [INFO] [1706239486.989379609] [gazebo_ros2_control]: Starting gazebo_ros2_control plugin in ros 2 node: gazebo_ros2_control
[gazebo-1] [INFO] [1706239486.989465076] [gazebo_ros2_control]: Loading parameter files /home/robotck/ros2_ws/install/dual_arm_gazebo/share/dual_arm_gazebo/config/dual_arm_control.yaml
[gazebo-1] [INFO] [1706239486.997542802] [gazebo_ros2_control]: connected to service!! robot_state_publisher
[gazebo-1] [INFO] [1706239486.999247405] [gazebo_ros2_control]: Received urdf from param server, parsing...
[gazebo-1] [INFO] [1706239487.016262191] [gazebo_ros2_control]: Loading joint: J1
[gazebo-1] [INFO] [1706239487.016349986] [gazebo_ros2_control]: 	State:
[gazebo-1] [INFO] [1706239487.016362582] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016371840] [gazebo_ros2_control]: 		 velocity
[gazebo-1] [INFO] [1706239487.016379531] [gazebo_ros2_control]: 	Command:
[gazebo-1] [INFO] [1706239487.016386328] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016465134] [gazebo_ros2_control]: Loading joint: Body
[gazebo-1] [INFO] [1706239487.016474482] [gazebo_ros2_control]: 	State:
[gazebo-1] [INFO] [1706239487.016481072] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016488085] [gazebo_ros2_control]: 		 velocity
[gazebo-1] [INFO] [1706239487.016494583] [gazebo_ros2_control]: 	Command:
[gazebo-1] [INFO] [1706239487.016501216] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016524337] [gazebo_ros2_control]: Loading joint: L-J1
[gazebo-1] [INFO] [1706239487.016532350] [gazebo_ros2_control]: 	State:
[gazebo-1] [INFO] [1706239487.016538927] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016545654] [gazebo_ros2_control]: 		 velocity
[gazebo-1] [INFO] [1706239487.016552278] [gazebo_ros2_control]: 	Command:
[gazebo-1] [INFO] [1706239487.016559237] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016571762] [gazebo_ros2_control]: Loading joint: L-J2
[gazebo-1] [INFO] [1706239487.016579479] [gazebo_ros2_control]: 	State:
[gazebo-1] [INFO] [1706239487.016585885] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016592457] [gazebo_ros2_control]: 		 velocity
[gazebo-1] [INFO] [1706239487.016598962] [gazebo_ros2_control]: 	Command:
[gazebo-1] [INFO] [1706239487.016605564] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016617902] [gazebo_ros2_control]: Loading joint: L-J3
[gazebo-1] [INFO] [1706239487.016625442] [gazebo_ros2_control]: 	State:
[gazebo-1] [INFO] [1706239487.016631972] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016639532] [gazebo_ros2_control]: 		 velocity
[gazebo-1] [INFO] [1706239487.016646146] [gazebo_ros2_control]: 	Command:
[gazebo-1] [INFO] [1706239487.016653090] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016664810] [gazebo_ros2_control]: Loading joint: L-J4
[gazebo-1] [INFO] [1706239487.016685905] [gazebo_ros2_control]: 	State:
[gazebo-1] [INFO] [1706239487.016698205] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016705434] [gazebo_ros2_control]: 		 velocity
[gazebo-1] [INFO] [1706239487.016712431] [gazebo_ros2_control]: 	Command:
[gazebo-1] [INFO] [1706239487.016718884] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016733892] [gazebo_ros2_control]: Loading joint: L-J5
[gazebo-1] [INFO] [1706239487.016741898] [gazebo_ros2_control]: 	State:
[gazebo-1] [INFO] [1706239487.016748310] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016755006] [gazebo_ros2_control]: 		 velocity
[gazebo-1] [INFO] [1706239487.016761580] [gazebo_ros2_control]: 	Command:
[gazebo-1] [INFO] [1706239487.016768236] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016778748] [gazebo_ros2_control]: Loading joint: L-J6
[gazebo-1] [INFO] [1706239487.016786294] [gazebo_ros2_control]: 	State:
[gazebo-1] [INFO] [1706239487.016792659] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016799148] [gazebo_ros2_control]: 		 velocity
[gazebo-1] [INFO] [1706239487.016805575] [gazebo_ros2_control]: 	Command:
[gazebo-1] [INFO] [1706239487.016811929] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016821567] [gazebo_ros2_control]: Loading joint: L-J7
[gazebo-1] [INFO] [1706239487.016829075] [gazebo_ros2_control]: 	State:
[gazebo-1] [INFO] [1706239487.016835682] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016843071] [gazebo_ros2_control]: 		 velocity
[gazebo-1] [INFO] [1706239487.016849694] [gazebo_ros2_control]: 	Command:
[gazebo-1] [INFO] [1706239487.016895437] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016909140] [gazebo_ros2_control]: Loading joint: R-J1
[gazebo-1] [INFO] [1706239487.016917175] [gazebo_ros2_control]: 	State:
[gazebo-1] [INFO] [1706239487.016923679] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016930548] [gazebo_ros2_control]: 		 velocity
[gazebo-1] [INFO] [1706239487.016937003] [gazebo_ros2_control]: 	Command:
[gazebo-1] [INFO] [1706239487.016943583] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016959188] [gazebo_ros2_control]: Loading joint: R-J2
[gazebo-1] [INFO] [1706239487.016967490] [gazebo_ros2_control]: 	State:
[gazebo-1] [INFO] [1706239487.016974096] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.016980510] [gazebo_ros2_control]: 		 velocity
[gazebo-1] [INFO] [1706239487.016986949] [gazebo_ros2_control]: 	Command:
[gazebo-1] [INFO] [1706239487.016993274] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.017005336] [gazebo_ros2_control]: Loading joint: R-J3
[gazebo-1] [INFO] [1706239487.017013132] [gazebo_ros2_control]: 	State:
[gazebo-1] [INFO] [1706239487.017019571] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.017026271] [gazebo_ros2_control]: 		 velocity
[gazebo-1] [INFO] [1706239487.017032615] [gazebo_ros2_control]: 	Command:
[gazebo-1] [INFO] [1706239487.017054292] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.017066193] [gazebo_ros2_control]: Loading joint: R-J4
[gazebo-1] [INFO] [1706239487.017074007] [gazebo_ros2_control]: 	State:
[gazebo-1] [INFO] [1706239487.017080925] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.017087777] [gazebo_ros2_control]: 		 velocity
[gazebo-1] [INFO] [1706239487.017094360] [gazebo_ros2_control]: 	Command:
[gazebo-1] [INFO] [1706239487.017100956] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.017114328] [gazebo_ros2_control]: Loading joint: R-J5
[gazebo-1] [INFO] [1706239487.017122232] [gazebo_ros2_control]: 	State:
[gazebo-1] [INFO] [1706239487.017129085] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.017135916] [gazebo_ros2_control]: 		 velocity
[gazebo-1] [INFO] [1706239487.017142548] [gazebo_ros2_control]: 	Command:
[gazebo-1] [INFO] [1706239487.017149251] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.017159774] [gazebo_ros2_control]: Loading joint: R-J6
[gazebo-1] [INFO] [1706239487.017180172] [gazebo_ros2_control]: 	State:
[gazebo-1] [INFO] [1706239487.017192868] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.017200199] [gazebo_ros2_control]: 		 velocity
[gazebo-1] [INFO] [1706239487.017206916] [gazebo_ros2_control]: 	Command:
[gazebo-1] [INFO] [1706239487.017213762] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.017226911] [gazebo_ros2_control]: Loading joint: R-J7
[gazebo-1] [INFO] [1706239487.017234666] [gazebo_ros2_control]: 	State:
[gazebo-1] [INFO] [1706239487.017241578] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.017248193] [gazebo_ros2_control]: 		 velocity
[gazebo-1] [INFO] [1706239487.017254720] [gazebo_ros2_control]: 	Command:
[gazebo-1] [INFO] [1706239487.017261241] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.017272375] [gazebo_ros2_control]: Loading joint: H-J1
[gazebo-1] [INFO] [1706239487.017283963] [gazebo_ros2_control]: 	State:
[gazebo-1] [INFO] [1706239487.017292118] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.017300573] [gazebo_ros2_control]: 		 velocity
[gazebo-1] [INFO] [1706239487.017307805] [gazebo_ros2_control]: 	Command:
[gazebo-1] [INFO] [1706239487.017314435] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.017325640] [gazebo_ros2_control]: Loading joint: H-J2
[gazebo-1] [INFO] [1706239487.017333512] [gazebo_ros2_control]: 	State:
[gazebo-1] [INFO] [1706239487.017340360] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.017346954] [gazebo_ros2_control]: 		 velocity
[gazebo-1] [INFO] [1706239487.017354099] [gazebo_ros2_control]: 	Command:
[gazebo-1] [INFO] [1706239487.017360566] [gazebo_ros2_control]: 		 position
[gazebo-1] [INFO] [1706239487.017429778] [resource_manager]: Initialize hardware 'dual_arm' 
[gazebo-1] [INFO] [1706239487.017611731] [resource_manager]: Successful initialization of hardware 'dual_arm'
[gazebo-1] [INFO] [1706239487.017775268] [resource_manager]: 'configure' hardware 'dual_arm' 
[gazebo-1] [INFO] [1706239487.017790133] [resource_manager]: Successful 'configure' of hardware 'dual_arm'
[gazebo-1] [INFO] [1706239487.017802629] [resource_manager]: 'activate' hardware 'dual_arm' 
[gazebo-1] [INFO] [1706239487.017809086] [resource_manager]: Successful 'activate' of hardware 'dual_arm'
[gazebo-1] [INFO] [1706239487.017909175] [gazebo_ros2_control]: Loading controller_manager
[gazebo-1] [INFO] [1706239487.068836479] [controller_manager]: Subscribing to '~/robot_description' topic for robot description file.
[gazebo-1] [WARN] [1706239487.080370142] [gazebo_ros2_control]:  Desired controller update period (0.01 s) is slower than the gazebo simulation period (0.001 s).
[gazebo-1] [INFO] [1706239487.080625948] [gazebo_ros2_control]: Loaded gazebo_ros2_control.
[gazebo-1] context mismatch in svga_surface_destroy
[gazebo-1] context mismatch in svga_surface_destroy
[gazebo-1] [INFO] [1706239488.899065900] [controller_manager]: Loading controller 'joint_state_broadcaster'
[gazebo-1] [INFO] [1706239488.971326153] [controller_manager]: Setting use_sim_time=True for joint_state_broadcaster to match controller manager (see ros2_control#325 for details)
[gazebo-1] [INFO] [1706239488.977276576] [controller_manager]: Configuring controller 'joint_state_broadcaster'
[gazebo-1] [INFO] [1706239488.977676420] [joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published
[ros2-4] Sucessfully loaded controller joint_state_broadcaster into state active
[INFO] [ros2-4]: process has finished cleanly [pid 20770]
[INFO] [ros2-5]: process started with pid [20814]
[INFO] [ros2-6]: process started with pid [20816]
[INFO] [ros2-7]: process started with pid [20818]
[INFO] [ros2-8]: process started with pid [20820]
[gazebo-1] [INFO] [1706239490.497724358] [controller_manager]: Loading controller 'Head_joint_trajectory_controller'
[gazebo-1] Exception thrown during init stage with message: expected [string] got [string_array] 
[gazebo-1] [ERROR] [1706239490.526122183] [controller_manager]: Could not initialize the controller named 'Head_joint_trajectory_controller'
[gazebo-1] [INFO] [1706239490.541068223] [controller_manager]: Loading controller 'Body_joint_trajectory_controller'
[ros2-8] Error loading controller, check controller_manager logs
[gazebo-1] Exception thrown during init stage with message: expected [string] got [string_array] 
[gazebo-1] [ERROR] [1706239490.558322016] [controller_manager]: Could not initialize the controller named 'Body_joint_trajectory_controller'
[ros2-7] Error loading controller, check controller_manager logs
[gazebo-1] [INFO] [1706239490.575401082] [controller_manager]: Loading controller 'Right_arm_joint_trajectory_controller'
[gazebo-1] Exception thrown during init stage with message: expected [string] got [string_array] 
[gazebo-1] [ERROR] [1706239490.586553576] [controller_manager]: Could not initialize the controller named 'Right_arm_joint_trajectory_controller'
[gazebo-1] [INFO] [1706239490.602357917] [controller_manager]: Loading controller 'Left_arm_joint_trajectory_controller'
[ros2-5] Error loading controller, check controller_manager logs
[gazebo-1] Exception thrown during init stage with message: expected [string] got [string_array] 
[gazebo-1] [ERROR] [1706239490.630282542] [controller_manager]: Could not initialize the controller named 'Left_arm_joint_trajectory_controller'
[ros2-6] Error loading controller, check controller_manager logs
[ERROR] [ros2-8]: process has died [pid 20820, exit code 1, cmd 'ros2 control load_controller --set-state active Head_joint_trajectory_controller'].
[ERROR] [ros2-5]: process has died [pid 20814, exit code 1, cmd 'ros2 control load_controller --set-state active Right_arm_joint_trajectory_controller'].
[ERROR] [ros2-6]: process has died [pid 20816, exit code 1, cmd 'ros2 control load_controller --set-state active Left_arm_joint_trajectory_controller'].
[ERROR] [ros2-7]: process has died [pid 20818, exit code 1, cmd 'ros2 control load_controller --set-state active Body_joint_trajectory_controller'].

**Comment by PANJIACHENG-98** [comment]
run： ros2 launch dual_arm_gazebo gazebo.launch.py 
at last， i can't load my controller,here is my controller yaml:
![屏幕截图 2024-01-26 114745](https://github.com/ros-controls/gazebo_ros2_control/assets/77319211/a38ace88-547c-42a9-816b-ba5aff4e7373)
the another three controller are in the same config

**Comment by PANJIACHENG-98** [comment]
beg for help please!!!!!

**Comment by PANJIACHENG-98** [comment]
here is the complete info:
![Uploading 1.jpg…]()

**Comment by PANJIACHENG-98** [comment]
![1](https://github.com/ros-controls/gazebo_ros2_control/assets/77319211/5bbb7cf9-f7ac-412f-b2dd-39c021d0df32)
![2](https://github.com/ros-controls/gazebo_ros2_control/assets/77319211/b9ed2f68-ce57-41b2-bb24-20fe6338bb11)
![3](https://github.com/ros-controls/gazebo_ros2_control/assets/77319211/26cbe336-de7e-453d-8d2f-5f490b70a80c)
![4](https://github.com/ros-controls/gazebo_ros2_control/assets/77319211/787d079f-a68d-4475-9b06-96b5d7275f1d)
![5](https://github.com/ros-controls/gazebo_ros2_control/assets/77319211/791a353d-418a-4f99-9975-73b715f0f889)

**Comment by Wiktor-99** [comment]
As stated in the documentation, you should only configure joints in your configuration file.(https://control.ros.org/master/doc/ros2_controllers/position_controllers/doc/userdoc.html)

**Comment by christophfroehlich** [comment]
> As stated in the documentation, you should only configure joints in your configuration file.(https://control.ros.org/master/doc/ros2_controllers/position_controllers/doc/userdoc.html)

correct. @PANJIACHENG-98 you name the controller *joint_trajectory_controller, but configured the type `position_controllers/JointGroupPositionController` which has only one parameter `joints` as written above.

**Comment by PANJIACHENG-98** [comment]
well solved thanks bro

**Comment by PANJIACHENG-98** [comment]
![image](https://github.com/ros-controls/gazebo_ros2_control/assets/77319211/2d8a8684-944e-4fd0-9802-92726f287c19)
