### ISSUE TITLE
Errors after launching demos: controller manager issue?

### ISSUE THREAD

**Issue by tera-bytes** [ros-controls/gazebo_ros2_control#274]
Whenever I try to launch any of the existing demos such as diff_drive, the gazebo simulation launches fine but I get these errors:
![image](https://github.com/ros-controls/gazebo_ros2_control/assets/78524031/4133aa40-e3d9-41d8-90ea-002fb8e88f2d)
So then any ros2 run command fails. I'm on ubuntu 22.04 using Humble. Any help would be much appreciated!

**Comment by SXYuuuuuu** [comment]
I meet the same error, it make me crazy

**Comment by ahcorde** [comment]
HI @tera-bytes 

can you copy the full trace instead of adding a picture?

**Comment by christophfroehlich** [comment]
And please add the exact version of ros2_control and gazebo_ros2_control (i.e., by running `ros2 pkg xml ros2-control -t version`)

**Comment by tera-bytes** [comment]
Hey, sorry about this but I actually managed to fix it today. I just deleted my old workspace and cloned and rebuilt. Everything works fine now. I didn't really do anything differently so I'm still not sure why I got those errors.

**Comment by bmagyar** [comment]
What was in your workspace? Any chance it had gazebo_ros2_control, ros2_control or ros2_controllers?

**Comment by tera-bytes** [comment]
> What was in your workspace? Any chance it had gazebo_ros2_control, ros2_control or ros2_controllers?
In the same workspace, I had cloned the github for the Ur5 Gazebo Simulation and it had gazebo_ros2_control and ros2_control.

**Comment by christophfroehlich** [comment]
closing this as it seems that it have fixed itself
