### ISSUE TITLE
ros2 eloqeunt I see that ros2_control and ros2_controller have a corresponding ros2_controller.

### ISSUE THREAD

**Issue by qinran123** [ros-controls/gazebo_ros2_control#393]
ros2 eloqeunt I see that ros2_control and ros2_controller have a corresponding ros2_controller.
I see that ros2_control and ros2_controller have versions, but gazebo_ros2_control doesn't. How do I get gazebo_ros2_control? Thanks.

**Comment by christophfroehlich** [comment]
Eloquent is end-of-life for over 4 years now. Please update to a newer distro. Be aware that gazebo classic will reach end-of-life in January, consider updating to gazebo and gz_ros2_control.

**Comment by qinran123** [comment]
So if I want to use gazebo-ros2-control, I can only update my ros2 version right? thanks!

**Comment by christophfroehlich** [comment]
Yes
