### ISSUE TITLE
Waiting for /controller_manager services issue

### ISSUE THREAD

**Issue by Kakcalu13** [ros-controls/gazebo_ros2_control#87]
Not sure if this is the right place to ask for the foxy ros2 control API.

I added the tag on URDF with this section:
```
<gazebo> 
	<plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control"> 
		<robotNamespace>/rrbot</robotNamespace>
		<parameters>$(find my_robot_description)/config/gazebo_ros_control_params.yaml</parameters> 
	</plugin> 
</gazebo>
```
The result from terminal
```

[spawner.py-6] [INFO] [1629924862.520367523] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[spawner.py-7] [INFO] [1629924862.614812317] [spawner_wheel_velocity_controller]: Waiting for /controller_manager services

```

full screenshot:

![image](https://user-images.githubusercontent.com/65916520/130864531-b22404df-23fc-4960-825b-40ee713f051e.png)

Is this a bug or am I just missing on something?

**Comment by sabrinaacardoso** [comment]
Hey there! Thank you so much for the answer.

I'm using Gazebo on version 11, would that be the most current version? I'm not familiar with the term new Gazebo.

**Comment by Kakcalu13** [comment]
That is the last and latest of classic gazebo. It will be on EOL (END OF LIFE) after 2024. New Gazebo is the new evolution and it will be supported for a very very long time. 

I use Citadel/Fortress on Foxy (about to hop into humble turtle)
